[[language]]
name = "bash"
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "yaml"
auto-format = true

[[language]]
name = "python"
auto-format = true
indent = { tab-width = 4, unit = "    " }
